export const ActionTypes = {
    ADD_CLIENT: "ADD_CLIENT",
    DELETE_CLIENT: "DELETE_CLIENT",
    UPDATE_CLIENT: "UPDATE_CLIENT",
    LIST_CLIENTS: "LIST_CLIENTS",
    ADD_CATEGORY: "ADD_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    LIST_CATEGORIES: "LIST_CATEGORIES"
}